# Generated by Django 2.2.12 on 2020-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
